ヘッダーを追加しました
sayuri0530/staticSitePractice pull request #1
Opened 2021-10-02 09:18 UTC by sayuri0530

ヘッダー部分を実装しました。

2021-10-02 13:24 UTC, oxo-yuta requested changes
一応リンクとして動くようにだけしておきましょう！
いまはリンク先が404エラー（リンク先のファイルが無いエラー）になってもOK！

2021-10-02 13:24 UTC, oxo-yuta commented on index.html
> +        <li>CONTACT</li>
ここはリンクなので、`li`タグの中に`a`タグを入れる形にしましょう！

```
<li>
  <a href="about.html">TOP</a>
</li>
...
```

2021-10-04 12:14 UTC, sayuri0530 commented on index.html
> +        <li>CONTACT</li>
修正しました。

2021-10-04 12:15 UTC, oxo-yuta commented on index.html
> +        <li>CONTACT</li>
OKです！

2021-10-04 12:15 UTC, oxo-yuta approved these changes
LGTM!

2021-10-04 12:16 UTC, merged